' Convert compiler errors to enable error highlighting in CodeLite.
The script tools/errconv.sh converts error messages generated by fcc907s.exe
to error messages that clang would generate. This enables CodeLite to
highlight the line containing the error.

Example:
*** main.c(7) E4110C: undeclared identifier `a'
 gets converted to
main.c:7:0: error: undeclared identifier `a'